### ISSUE TITLE
App shuts down :-(

### ISSUE THREAD

**Issue by JimZam** [maheini/FreeStyle-Libre-3-patch#9] opened 2022-09-12 22:19 UTC
Goodnight from Spain. Thank you for this so expected app!!!! In my case I have to reboot my phone to make it work and it shuts down everytime in the carbohydrate selection page.
Once again thank you for sharing your work with us.
Regards

edit: this is the error I get
![Screenshot_2022-09-13-17-48-43-060_com miui bugreport~2](https://user-images.githubusercontent.com/23319786/189948861-6f1940d3-e93f-40a7-8eaa-f98212b35c4d.jpg)

**Comment by maheini** [comment] 2022-09-14 20:01
Thanks for the log file. I guess the libre 3 app is crashing, not Juggluco? Do you use a special System like: No google services, custom ROM, root, old/new android version? And is the original libre 3 app working as intended on your phone?

Currently, I do not know what could have caused this crash. But with further information, we will find a solution.

**Comment by JimZam** [comment] 2022-09-14 20:42
Good evening. It's the patched app which crashes, not Juggluco. I have tried Freestyle Libre 3 versions 3.4.0 and 3.3.1 and only 3.3.1 works, version 3.4.0 crashes at start, no way to mske it work.
The patched app only works rebooting after installing, deleting cache does't make any change. Once rebooted it works until I select mg/dl and confirm it, then crashes.
My phone is rooted, ROM xiaomi.eu, Android 10.
Thank you again for your work.
Regards

**Comment by yoshimo** [comment] 2022-09-15 06:15
Libre Apps try to detect root and xposed modules.
If they do, they don't print a message about root, they crash.  Probably a WhiteCrypto feature, the solution they use to protect their app from reverse engineering.
Magisk alone might not be enough to successfully  fool the app.

**Comment by JimZam** [comment] 2022-09-15 21:27
https://insulinclub-de.translate.goog/index.php?thread/33793-libre-3-auf-gerooteten-smartphones-funktioniert/&_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=es&_x_tr_pto=wapp

**Comment by JimZam** [comment] 2022-09-15 21:28
You are right, it seems it's due to been rooted...

**Comment by maheini** [comment] 2022-09-17 09:59
As @yoshimo stated (thanks), it's most likely because of your root and therefore I will close the issue as solved.

If you still facing other problems, feel free to open a new issue.

**Closed by maheini** 2022-09-17 09:59 UTC
